### ISSUE TITLE
Weekly report

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#116]
```
Could the bot report weekly:
Total Members
New Members
Members that left
Members that were banned
```

**Comment by chrislennon** [comment]
Still think this may be nice to have. Would we wish to do this on sql?

[An Alternative](https://github.com/PaddoInWonderland/PaddoCogs/blob/master/statistics/statistics.py) we could implement instantly on red - may also give an idea how to write it up ourselves.

**Comment by chrislennon** [comment]
Don't do what I said, at least on Red. Will require giving away far too many permissions to it. I think this is going to have to be a database of some sort 😭
