### ISSUE TITLE
getinfo, limit characters

### ISSUE THREAD

**Issue by Reynbow** [otter-computer/GaymersBot#121]
Make it so there are invalid characters. If the bot reads a non legal character it just says "Oops, no emojis or special characters allowed!" or something to that effect. And limit the characters if you have to to make Spazer stop having seizures.

Perhaps even have limited fields? Limit it to 5-10 entries maybe? Seeing how this seems to be causing emotional distress for Spazer. 😆

**Comment by jmariondev** [comment]
What should be considered legal? A-Z, a-z, 0-9, and what symbols?

**Comment by otter-computer** [comment]
`RegExp('.', 'g')` plz 😒
