### ISSUE TITLE
Emoji usage stats

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#130]
It would be funny and interesting to record the usage of emoji on our server.

**Comment by otter-computer** [comment]
For "emojianalysis"?

![osm7uul4211y](https://cloud.githubusercontent.com/assets/2439407/21006665/3cee2e1c-bd3a-11e6-96f4-ca11ef22d443.jpg)

**Comment by chrislennon** [comment]
given the recent 🌮 events - would be somewhat interesting. However don't think its probably a good thing for us to start trawling through non `!` prefixed - especially if our only option is to send it off to sql (Assuming no file persistence on Elastic Beanstalk?).
