### ISSUE TITLE
Connection monitoring

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#131]
DiscoBot appears to have been losing connection to Discord. Sometimes it seems to reconnect, but other times it will need to be manually re-deployed. This isn't optimal. Ideally DiscoBot would be more aggressive about staying connected.

**Comment by otter-computer** [comment]
Any recent incidents or can I go ahead and close this? From what I've seen the bot seems to have been fairly stable recently.

**Comment by jmariondev** [comment]
We've not had an incident with this recently, perhaps there was an issue with an older version of discord.js that didn't handle reconnecting properly? Either way if we continue to have issues we can always shard the bot in the future 🤷‍♀️ .

**Comment by jmariondev** [comment]
After today's Discord outage, the bot did not reconnect automatically. I think we should add a cron to just verify connection every minute or so. I will see if there's something in the API we can use as a heartbeat.

**Comment by otter-computer** [comment]
Cron 👎👎👎 Crons are bad and I think is what's causing our deploy issues. Afaik there's a native onDisconnect method or something that we should listen to instead.

**Comment by jmariondev** [comment]
There should be a back-off timer for reconnecting, should we just use a thread sleep?

**Comment by otter-computer** [comment]
I think any time it can't connect it errors in node, and when it errors in node then amazon auto restarts the process. I'm not 100% that's what happens, but I *think* that's true... Still, we should handle it more gracefully anyways.
