### ISSUE TITLE
Ping the online admins and moderators when someone joins the #welcome-room

### ISSUE THREAD

**Issue by brandon-a** [otter-computer/GaymersBot#134]
DM or mention (to be decided) the online (not idle, do not disturb or invisible) admins and mods when a new user joins the server in the #welcome-room.

**Comment by jmariondev** [comment]
There is debate how this should work. The current concensus is that we should not use a role mention (ie (at)Admin or (at)Moderator) because this will ping offline admins.

Mentioning available admins in the #welcome-room welcome message was suggested, but this was called "unclean".

**Comment by brandon-a** [comment]
It doesn't look like this will be necessary.

**Comment by otter-computer** [comment]
^ I think everyone's kinda on top of it, if and admin really wants notified then just turn on channel notifications I guess.

**Comment by jmariondev** [comment]
We'd like to revisit this idea. Personally I stick by my suggestion of mentioning individual staff members based on escalation logic in welcome-room directly.

**Comment by Reynbow** [comment]
I really do think this is the way to go forward with this situation. We shouldn't be adding new roles for the Welcome Room. Not only is it messy (and ultimately I think it would make people be even more desensitized to the mention) but we should NOT be disrupting UX for members. That's terrible design practice. You should only disrupt UX if absolutely necessary.

Another thing to mention going forward with this. It might be a good idea for the bot to ping us in the moderators room rather than directly in the welcome-room. Just something simple like "%user% needs help in the Welcome Room". 

Fairly simple.

**Comment by jmariondev** [comment]
My thoughts on it happening in the moderators chat is that it would be nicer UX to have the mention bring the moderator directly to the welcome room, rather than requiring they go into one room just to move to the next.

**Comment by brandon-a** [comment]
I agree with John here.

**Comment by Reynbow** [comment]
That's fair enough. I was thinking more about the Members UX in this situation though. Something affecting us shouldn't be put before something affecting users. But it's not a huge deal I suppose.

**Comment by jmariondev** [comment]
I see that as having a neutral effect on the user experience, while improving our usability.

**Comment by Reynbow** [comment]
Well, it could look bad for users seeing the bot alert us. But ultimately not a huge deal either way. As long as it's implemented, that's all that matters.

**Comment by jmariondev** [comment]
If there are no other objections to this, we can go on an implementation?

**Comment by otter-computer** [comment]
**I HATE THIS.**

..loljk do it 😄

**Comment by brandon-a** [comment]
I still think having the @Welcome role would be best, that way we can add and remove it from ourselves when we do and do not want to be notified.

**Comment by Reynbow** [comment]
We absolutely should not have a separate role for this. I explained why above. 
It's a seriously bad idea. From a user point of view alone it's terrible. Please do not do this "welcome" role thing.

**Comment by jmariondev** [comment]
We're dropping this idea?

**Comment by brandon-a** [comment]
I would say so since we may get rid of the welcome room, but that is still
up for debate.

**Comment by jmariondev** [comment]
Re-opening this after discussion in gaymers-discord/administration#23. Here's how this is planned:

> 10-15 minutes after a user joins, a timer is fired. If the user has not said anything since joining, the bot mentions them again in welcome-room reminding them to introduce themselves. If the user has said something, the bot sends a message to mod-tracker with `@here` reminding staff to take a look at the welcome-room. If the user was manually caught before the timer, obviously no action is taken.
