### ISSUE TITLE
!Timeout should remove the member role

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#152]
The timeout command needs to ~~revive~~ remove the member role from users to stop them being able to talk in other channels.

**Comment by Reynbow** [comment]
And by revive, he means remove. 

So it needs to remove the member role, checking to see if they already had it. (Just in case we want to restrict someone who's only in the welcome room)

And then it needs to add it back after. Yay! And not say the welcome message again... 😂

**Comment by otter-computer** [comment]
This was fixed in f3aef7c
