### ISSUE TITLE
Music Streaming Features

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#169]
We've cycled through multiple music bots and the free ones *aren't great*. We should at least evaluate adding this to Disco.

Another note in our testing is that we should look into volume equalization for this.

**Comment by otter-computer** [comment]
Just an update, I looked into this ages ago.

...I hate it :|

I have no useful input to add.

**Comment by chrislennon** [comment]
I came, I saw, I failed. Attempted to run a music bot on lambda without an ec2 box, while it worked it certainly wasn't fun. Code [here](https://github.com/chrislennon/serverless-music-bot) in case someone is braver than I.

**Comment by chrislennon** [comment]
Proposing to close this issue as we have implemented [Red](https://cogs.red/) - whilst the hosting situation is fine for now - we should look at moving this to a shared solution (AWS if we figure out our billing).

**Comment by otter-computer** [comment]
FWIW if we ever reopen this it will likely be a separate bot anyways.

**Comment by chrislennon** [comment]
Lucio (the Red bot) has gained quite some traction. During usage we have uncovered there are some issues. As this source code is maintained over at https://github.com/Twentysix26/Red-DiscordBot we have two options:

1. Continue to use Red and offer up patches to their issues, in particular the issue that users not in the music channel can requests songs, likely related to [this issue](https://github.com/Twentysix26/Red-DiscordBot/issues/494)

2. Build the functionality we wish ourselves

I'm fairly comfortable with python so don't mind going down the patching route, however given the scope of Red is far beyond Music, I propose we generate our own bot for our own selfish means 😄

**Comment by chrislennon** [comment]
I don't see any discussion here, but i do see the fork of Red, should I assume that's the route we are going? Not what I said above but happy to do so 😉 @LuaMilkshake

**Comment by jmariondev** [comment]
The idea was to at least patch Red for our main issue now, and look at developing our own solution long-term.

**Comment by tekulvw** [comment]
I'm one of the collaborators for Red, found you guys through the issue you linked above.

If you guys would like to help us create a better audio solution I think that would be great. We're actually in the middle of a massive rewrite of the entire bot and right now we've got one guy working on it who is going to be busy for at least the next month and probably won't be able to contribute. So, if you guys would like to, the floor is open as to new features for AudioV3 and we're definitely open to getting some more developers involved. What do you think?

**Comment by chrislennon** [comment]
@tekulvw thanks for stopping by, sounds interesting. As you may of gathered from above we currently only use the music features from Red. I initially ruled out the contribute back approach as the majority of our codebase is nodejs based. However a user has stepped forward to investigate one patch for an issue as a start point.

I'll raise this further with the group as writing duplicate functionality for our own bot is far from the most efficient solution 😋. I'll have the gaymers stop by your discord server if they are not there already so we can look at contributing. (I go by the username leapyearboy)

**Comment by tekulvw** [comment]
Oh, I didn't realize you guys were nodejs based :sweat_smile: (serves me right for not looking into it further).

However I do agree with you that writing duplicate functionality is really a waste of time and effort for the both of us. Feel free to drop by in discord and we can definitely talk some more about this, I'm looking forward to it. (I'm `Will (tekulvw)`)

**Comment by chrislennon** [comment]
Found some time to attempt to replicate this issue. Sadly unable to replicate:
- Issue was that a member was able to trigger playing of a track using `?play` whilst either:
  - not in a voice channel at all
  - in a voice channel that is not the specific #music channel

Checking over Red's code base there has been no notable changes to the audio cog, I will reach out to the old ticket on Red's repo to see if the user had steps for replication.

For now I will close this issue, if anyone finds steps for replication please reopen it.

We have not forgotten the Red Dev's offer to contribute with them, for sure we will be in touch - but likely not over this issue any more! 💃
