### ISSUE TITLE
Permissions Auditing

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#170]
We recently ran into an issue where non-Members could talk in various text channels. We can use the bot to define a set of rules about permissions that should never be the case (ie only staff-like roles have administrative perms, non-Members are mostly restricted, etc). These tests could run each time a permission update happens and notify staff if a change breaks the rules.

**Comment by chrislennon** [comment]
Is this still an issue? 
The way I'm reading it we will need to keep a list of rooms and their permissions within the bot, as I imagine there will be exceptions for restricted/admin rooms. Sounds like a load of hassle.
👎 (I'm on an issue purge 🤗)

**Comment by jmariondev** [comment]
My idea here was more of a sanity test suite for permissions. There's been multiple instances of Discord's permissions complexity causing us to fuck up some permissions like not allowing people to talk in some channels, allowing restricted users to still use some less-popular channels, and accidentally giving everyone certain moderator permissions. In that last instance, had everyone not gotten the "you don't have your moderator perms because you don't have 2fac", we may not have even noticed.

This would run on the permissions changed event or whatever, and would `@Admin` if a sanity test failed.

I argue that this is still a valid feature.

**Comment by otter-computer** [comment]
I would argue we just need to sit and work out our actual permission structure correctly. Without a proper review of what roles have what permissions we can't build a test suite. The permissions of roles haven't been looked at from the top down since the inception of the server, and have just been added to when necessary, or when Discord decides to silently add more, without reviewing how they affect each other.

**Comment by otter-computer** [comment]
OK I MEAN we can do this, but only after we do that up there first! ^

**Comment by chrislennon** [comment]
Raised on admin board, will reopen or create new issues as the discussion progresses there.
