### ISSUE TITLE
Error Handler

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#187]
I would like to implement a handler for all of our errors that sends a message to the developer channel when an exception or error condition happens. My hesitation with this is that I'd like to have the server and channel configurable via a config file but that's not been possible with our history with Heroku.

**Comment by chrislennon** [comment]
Does the config file [PR](https://github.com/gaymers-discord/DiscoBot/pull/239) I put in unblock this now?

**Comment by chrislennon** [comment]
Was looking around a little on what/how this would starting being implemented, would recommend giving [this](https://www.joyent.com/node-js/production/design/errors) a read - lots of nice info there.

**Comment by chrislennon** [comment]
You can build a handler for Winston now to send logs towards a dev room if you wish, added a logger to assist with the new AWS work. If you still want to forward errors elsewhere can do that now too ;)
