### ISSUE TITLE
Update/Remove !status Command

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#188]
Now that we're not on Heroku, the `!status` command doesn't work. Should we either update this to work somehow with the new system or even just remove the command all together?

**Comment by jmariondev** [comment]
Are we just going to bin this?

**Comment by otter-computer** [comment]
Either that or we make it work with AWS instead. It'd be nice to have I guess. 

Although what would be *nicer* is to have it done via a webhook with EB, that way we can get notifications of failed deploys, instance restarts, etc. I started looking at that before and haven't gone back to it yet.
