### ISSUE TITLE
Fix !help with regard to permissions

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#189]
Currently, `!help` just ignores commands that require permissions. We should add an addendum to the `!help` output when used in a DM that clarifies that running `!help` on a server will also include permissions-based commands. We can then use the user context from server uses of `!help` to build a better command listing. This is probably a good opportunity to clean up the help output to also include information about which commands can be used in certain channels, or in DMs.

**Comment by chrislennon** [comment]
@LuaMilkshake I fixed it!! Or more just rewrote it 😄
