### ISSUE TITLE
Add admin command to DM all members with no roles.

### ISSUE THREAD

**Issue by brandon-a** [otter-computer/GaymersBot#194]
Low priority, it would be nice to be able to DM all members with no rules reminding them to make their introduction or the bot will kick them in 24 hours. Just to purge the server of users online users who have never tried to gain access.

**Comment by jmariondev** [comment]
Since we no longer have scheduled tasks, would it be better to implement this as a manual command? It would be something that can just be run every so often for pruning.

**Comment by chrislennon** [comment]
^ what he said. I looked at the PR, I can assist in adding it a manual (or automated) command. Decide on the politics and I can throw some changes together 🤓 ... otherwise get this issue out of here 😘

**Comment by jmariondev** [comment]
This is pending a decision in #256.

**Comment by chrislennon** [comment]
closed as per #280
