### ISSUE TITLE
Improve `!role` usability

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#197]
Users frequently get confused with the role commands. They will typically try a command like `!setrole`, probably because of `!set18`.

From discussion in the developer chat, we think the following should be implemented:

- If `!role` is used without an operator (ie `!role Overwatch`), toggle the role on that user. (@ThomasShaped)
- If `!role` is used without a valid operator or role, or used on its own, output a better help message that includes both command usage and available roles. (@Reynbow)
- Add aliases for `!setrole` (to `!role set`) and `!unsetrole` (to `!role unset`). (@ThomasShaped)

**Comment by otter-computer** [comment]
#204 can likely be added at the same time

**Comment by jmariondev** [comment]
Leaving this open for the last point to be implemented (`!setrole` et al aliases).
