### ISSUE TITLE
Add exception to `command.onlyIn` for developer chat

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#198]
@ThomasShaped suggested that we add an exception for the developer chat room to the `onlyIn` chat parameter so that commands can be used in the developer chat regardless of if they're designed to be there.

**Comment by jmariondev** [comment]
In my opinion this further increases the need to be able to define runtime parameters such as what the 'developer chat' is called on a server.

**Comment by jmariondev** [comment]
Do we want to add exceptions for elsewhere, or just for dev chat? ie moderators/admin ?

**Comment by otter-computer** [comment]
I think we can probably just leave this tbh, complicating logic for minimal gain 🤷
