### ISSUE TITLE
Mention users in #appeals when they're restricted

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#201]
This proposal is still being discussed, but it may be helpful for the bot to mention users with a little blurb in the appeals channel to direct them to the only channel that they'll be allowed to use.

**Comment by jmariondev** [comment]
@Reynbow's suggested message:

> Hello $user, you're currently restricted and unable to send messages in the rest of the server. An Admin or Moderator will be with you shortly. Take the time to acknowledge why you are here.

@brandon-a suggested the addition of
> This would also be a good time to present your thoughts on the matter.

**Comment by brandon-a** [comment]
After further thought, I think manual mentions are the best way to handle this, so this is not needed.
