### ISSUE TITLE
Handle users that are restricted while in VC

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#202]
Currently, restricting a user doesn't do anything to their ability to talk if they're already in a voice chat. We should either move them to AFK, mute them, or remove them from voice.

(per @Reynbow )

**Comment by otter-computer** [comment]
I assume you mean using the `!timeout` command? I would agree that we should handle that instance but if the restricted role is added manually then the admin/mod can handle the VC removal themselves, we shouldn't be checking for that on every user update.

**Comment by jmariondev** [comment]
We would put such a thing in the block already handling when a user becomes restricted: [/events/memberUpdated.js#L143-L147](https://github.com/gaymers-discord/DiscoBot/blob/080aef470c39f1c2c79a1b328ab36acf6e78ad82/events/memberUpdated.js#L143-L147)

Handler is here: [/events/memberUpdated.js#L68-L86](https://github.com/gaymers-discord/DiscoBot/blob/080aef470c39f1c2c79a1b328ab36acf6e78ad82/events/memberUpdated.js#L68-L86)

**Comment by otter-computer** [comment]
THAT'S COOL I forgot we already had a handler for checking member status anyways 😳 

DO IT.
