### ISSUE TITLE
Add age of account to User Logs when someone joins

### ISSUE THREAD

**Issue by Reynbow** [otter-computer/GaymersBot#207]
So basically have it so that in user-logs when someone joins (it currently just says they joined and when they joined) it shows the age of the account as well. Here's an example of another bot showing the date the user joined Discord http://i.imgur.com/reBJYJw.png as well as the date joined on the server.

**Comment by jmariondev** [comment]
I *think* [this](https://discord.js.org/#/docs/main/stable/class/User?scrollTo=createdAt) is the relevant part of the API?

**Comment by Reynbow** [comment]
Oh also, when automod comes around, you could use the data retrieved from this (say if the account is less than 48 hours old) to mark them with a few points straight away. In essence giving them a "soft restriction"

**Comment by brandon-a** [comment]
I don't know if we want that to clutter up user logs or just make a command for it, but I'm not sure either way.

**Comment by Reynbow** [comment]
It wouldn't add clutter, it would be on the same line as the current information.

**Comment by brandon-a** [comment]
It depends on how it will appear.

**Comment by Reynbow** [comment]
I think a single line for record keeping is more important than whatever "clutter" it might cause. Search is available to sort if you're looking for something. Clutter shouldn't be the concern.

**Comment by otter-computer** [comment]
I'll probably just replace/alias `!joined` with `!info` or something for a manual version of this.

As for adding it to user logs the embeds need tidied up anyways. It shouldn't make it get much bigger or anything like that.
