### ISSUE TITLE
!timeout admin command

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#21]
Allows admins to give a user a timeout, setting the restricted role on someone for a set period of time.

**Comment by otter-computer** [comment]
Maybe something along the lines of `!timeout @user 30` to give the restricted role to a user for 30 mins.

**Comment by otter-computer** [comment]
I can see there being issues if Elastic Beanstalk migrates in that time and the role not ever being removed... But if we have some for of data storage and it just checks every so often then we can work something out?

**Comment by chrislennon** [comment]
i have started work on this by hijacking the user changes and checking if more than 5 mins have passed since last run, this could trigger of other check/create/delete rooms etc
https://github.com/gaymers-discord/DiscoBot.js/commit/643f16866e136cc852d57f965d78720b4c24d21c

**Comment by otter-computer** [comment]
This was added in #50
