### ISSUE TITLE
Read a configuration file for runtime parameters

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#210]
The bot should read some kind of configuration for runtime parameters. Examples of such parameters would be log level (see #211), error reporting channel (see #187), and role lists (the contents of `roles.js`).

**Comment by chrislennon** [comment]
@ThomasShaped wish to handle this the same way you are handling your local config json? Sounds like we can merge it with the environment variables etc. 
Can you give us an example? Maybe create a config.example.json for new users to fill?

**Comment by chrislennon** [comment]
I made some progress with this on #239
