### ISSUE TITLE
Use a proper logging framework

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#211]
It would be nice to utilize the features of a mature logging framework (levels, output settings, etc). From a cursory search, we could use something like [js-logger](https://github.com/jonnyreeves/js-logger).

**Comment by jmariondev** [comment]
@ThomasShaped @chrislennon Can we create and include a `config.json` somewhere between the repo and EC2? Like in some kind of build step?

**Comment by otter-computer** [comment]
Tbh I don't really see the point. We should just utilise `console.log()` properly with a guide on where/when/how we log info. The logs are all easily accessible from inside EB - and can possibly even be piped to cloudwatch for easier management.

**Comment by jmariondev** [comment]
Log levels are my main desire for something like this. Since it can be switched in runtime, we can pepper the code with various things like DEBUG-level messages (like when you were debugging the crons) and have them enabled based on the runtime environment.

This would also help with log formatting standardization, since the format of the output is defined by the logging framework and only the messages are included at the logging call.

I also imagine Amazon's logging features work with the typical logging formats to filter on things like the timestamps, levels, etc.

**Comment by otter-computer** [comment]
I don't see why it needs to be configurable. Logging is only useful to us *after* something is broken so having to go in and turn it on then wait for whatever it was to happen again seems like excess steps.

I'm just saying we should log all the time anyways and have an automatic retention policy on the logs we keep (afaik we already have this in place, we just barely log anything useful)

Also, the default console already comes with things like `console.info` and `console.warn` anyways, we don't really need any more levels IMO (I mean considering we have 0 at the moment)

**Comment by otter-computer** [comment]
I mean have you even seen the source of that js logger? It's a wrapper on the `console`object...

![image](https://cloud.githubusercontent.com/assets/2439407/24325836/e431a6fc-11a1-11e7-89c6-8d1d24c6060d.png)

**Comment by jmariondev** [comment]
My issue with those calls is that on stdout (does `console.error` output to stderr? does amazon's log differentiate between stdout and stderr?) it all looks the same. Having a greppable string appended to the front of the log (a la Apache's style) makes log auditing much easier.

I do see what you mean about using debug logs being a reactive thing, but I think certain "bread-and-butter" debug messages would be useful. While I was debugging Junkbot ignoring me, I wasn't sure if it was even calling the message handler. I would have solved that issue much quicker if I could flip on verbose debug logging and see that it was getting my message, and it was ignoring it because I was restricted.

Regarding that framework ultimately just calling `console.*` anyway, the value is its formatting and option to also `tee` logs off to the FS as well. I don't think we'd want files in prod, but in a debug environment it could be helpful to write to stdout/err and a file to grep through.

**Comment by otter-computer** [comment]
According to the [node docs](https://nodejs.org/api/console.html) `console.warn` and `console.error` both write to `stderr`, yeah.

I get what you mean about the logs being useful for debugging but I just don't understand the need to turn them on and off. If we have them why not have them on all the time anyway? That way if something does go wrong we'll already have the logs for it.

I think we just need a standard way of writing debug messages - whether we have a library handle appending the time/date/whatever or we just make sure we do it ourselves we just need to add them everywhere useful.

**Comment by jmariondev** [comment]
If we can log debug in runtime without worrying storing all of that junk, then I'm all for it. The reason I want to switch off DEBUG in prod is that the amount of data that would create is massive even if the only DEBUG messages are in the message handler.

I think that relying on us to write the format correctly every time in every log call is a bad idea (DRY?). Centralizing that *at least* into our own function would be better, but this is the JS world where you import everything (`left-pad` anyone?).

**Comment by otter-computer** [comment]
If the logging framework is gonna make that easier on us then I say we just add it for the formatting.

And if it's gonna eventually become _too_ verbose then if we're already using that framework then we can go ahead and start utilising the levels system that it already has I guess.

Regardless, **we need dem logs.** Then we can worry about how much of it to display when we see what we get back.

**Comment by jmariondev** [comment]
Fair enough. In the initial implementation we can add those "bread-and-butter" calls and then tune them based on what we see fit later.

**Comment by otter-computer** [comment]
I added `log-timestamp` as a dependancy in #237. It should at least standardise the time output on log messages.
