### ISSUE TITLE
!timeout does not unrestrict members properly

### ISSUE THREAD

**Issue by brandon-a** [otter-computer/GaymersBot#212]
I have not tested it thoroughly but it did not remove the restriction from someone with emojis at the beginning and end of their name.

**Comment by brandon-a** [comment]
So it seems to remove the restricted role, but does not give them the member role again, which prevents them from speaking.

**Comment by otter-computer** [comment]
#166 has a fix for this btw, but it's still WIP. I can maybe take a look at it in a bit/tomorrow to get this deployed fast.

**Comment by jmariondev** [comment]
This was the intended behavior when we first implemented the 'Member' role. We've had discussions about giving back the Member role after a timeout/unrestriction. This would be trivial to implement, but I've now realized the issue with welcoming the user in #general and DMing them the onboarding information. I'll need to find a way to suppress this onboarding process when we re-member them.

**Comment by otter-computer** [comment]
FYI `!timeout` command is disabled. I'll reenable it once I've  updated it to work with the new database system. Included in that will be fixes for this.
