### ISSUE TITLE
Have the bot mention additional roles that can be added.

### ISSUE THREAD

**Issue by brandon-a** [otter-computer/GaymersBot#217]
When a user sets their region, or sets18 have Kirby say something like:

> @USER, I've set your region! You may also type !role to learn about other roles you can add! Please direct suggestions to one of the mods or admins.

Or a similar message.

**Comment by jmariondev** [comment]
This is merged but not showing up in prod, does the bot need to be redeployed? @ThomasShaped @chrislennon
