### ISSUE TITLE
!role command doesn't accept roles unless they are specifically named

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#219]
!role command doesn't accept roles unless they are specifically named, usually in Title Case. Recently happened with the creation of the `CS:GO` role that can't be added due to the way we transform the role name. 

We should refactor how roles are looked up from Discord so we can avoid this.

**Comment by otter-computer** [comment]
Should probably be integrated with #197 and #209

**Comment by jmariondev** [comment]
Also see #178
