### ISSUE TITLE
!member does not trigger welcome message or logging

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#220]
Command is unreliable at triggering these events, should consider manually triggering them.

**Comment by chrislennon** [comment]
Whats the specific failure of the command? It looks okay to me. 😟

**Comment by chrislennon** [comment]
It could be related (or not) but I have also now experienced this issue when giving a user member status without using the `!member` command.

I haven't been able to replicate it - if anyone finds a reliable way to replicate it, please ping me.

User it happened to was granted access on `Tue Jul 11th, 2017 at 11:32 AM`
