### ISSUE TITLE
Allow the display of messages using message IDs.

### ISSUE THREAD

**Issue by brandon-a** [otter-computer/GaymersBot#226]
We can currently use a user ID to display that user in a channel that user is not in. 

It would be nice to be able to use a message ID to record or display a message in one of the hidden channels.

For example the command can be something like:

`!displaymessage 306059585486192641`

which would cause the bot to respond saying what the message contents are, and where the message was posted. This would be more reliable than screenshots and might be useful for reports where we don't know if we want to trust screenshots, as well as I think it would just be a useful command in general.

[Here's a link to the message object in the discord API.](https://discordapp.com/developers/docs/resources/channel#message-object)

**Comment by otter-computer** [comment]
I like this

**Comment by jmariondev** [comment]
I looked into this and it looks like getting a message object from just an ID is a bit tricky? I'll continue to research it tomorrow morning while I'm at work. 😄 
https://discord.js.org/#/docs/main/stable/class/Message

**Comment by otter-computer** [comment]
I do it for Mercy, and yeah it's a bitch. Afaik you also need the room it was in as you can only find messages via the channel? I think?

**Comment by otter-computer** [comment]
Here's a code snip from where I do it in Mercy:
```
commandMessage.guild.channels.find('name', message.channelName).messages.get(id).delete();
```
So as you can see I look up the channel via the name that has been stored previously in Mercy's internal message store, then I look up the ID inside that channel.

We'll likely have to do something similar here either by giving the channel (via a mention I guess) or just loop over all channels in the server until we find one (kinda slow).

**Comment by jmariondev** [comment]
Ah yes it looks like this is a limitation of the underlying API. You can't just look up a message from its snowflake, you need to index it on a channel ID. I reckon then that we'll have to iterate the channels and brute force a search :stuck_out_tongue:.

https://discordapp.com/developers/docs/resources/channel#get-channel-message
