### ISSUE TITLE
Remove user logging features

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#235]
Now that audit logs are implemented in Discord itself I would like to open a discussion into removing the user logging features from the bot. Discord's version is much more feature complete and integrated than our version will ever be, plus it is less code that needs to be maintained.

Still, obviously if we chose to go ahead with removing these features/channels it would be *after* Discord implements the features on all mobile clients.

**Comment by brandon-a** [comment]
I think this should be pretty safe to do so, but before we do, we should double check that our logging feature doesn't keep track of anything that we still want to keep that audit log does not. But it's likely we're covered.

**Comment by otter-computer** [comment]
From some comments in Moderator chat it seems like people are generally in favour of this. However there are a few caveats that might swing things the other way:

- We would lose notification of join/member/leave events as audit logs doesn't track this information yet.
- I've discovered that the maximum retention time of Audit logs is only 90 days, and Discord is currently unwilling to extend this. Channel history is infinite so if we want to keep continuous records it would be best to leave things as they are.

I'll need to do some investigation into whether things like ban/kick reasons are saved for longer as that is valuable information to keep around - but we also have #violations for that too, so I think it might just be redundant information.

Personally I don't *really* see a huge value in the joined event messages - considering if we're interested we have the `!joined` command. Leaving is a little more interesting to watch for though, but I don't think it's a super hard requirement. Granting membership *is* logged as modification of roles is logged in audit logs.

**Comment by chrislennon** [comment]
closing this issue, further comments taking place in admin repo. Any actions will result in reopening this ticket or creating new ones.
