### ISSUE TITLE
Add a command to show message edit history

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#241]
While poking through the `discord.js` docs I found a field on message that looks like it holds message edit history? I imagine this is still contingent on the discordjs cache, but perhaps we could have a `!diff` command or something so I can't be cheeky with messages anymore 🙊 .

https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=edits

**Comment by otter-computer** [comment]
We already have a similar event that's currently disabled that will post to #message-logs when a message is edited, although it's been disabled because it counts several things as message edits like loading an embed and stuff. I never did go back and look at the logic for it.

**Comment by jmariondev** [comment]
If we're looking at binning #message-logs, though, that will affect the usabilty of that feature.

**Comment by otter-computer** [comment]
It would only be #user-logs that we were looking at binning for now I think since Discord's audit logs doesn't deal with messages. It could just be refactored to work somewhere else though, it'll need looked at anyway if we wanted it reactivated 😄

**Comment by chrislennon** [comment]
I have opened #321 to add this functionality again, it appears to operate correctly with embeds and general message edits. What other test cases were causing an issue in the past?

**Comment by otter-computer** [comment]
Image attachments and link previews loading are classed as an “edit”. This probably won’t be an issue for an actual command though. 

I have similar functionality to this command built that will log when a message is edited in #message-logs, but is disabled because of above. That’s the only reason the logging is turned off.

**Comment by chrislennon** [comment]
Yeah it seems they are suppressed now. I thought I found an edge case where an image with no text, then edited to contain text was causing an issue - however it appears I was just [a fool](https://github.com/gaymers-discord/DiscoBot/pull/321/commits/0c01d9f4b6bf292facd1a63d3841a9f85f95e46c)
