### ISSUE TITLE
Changing Region(role) Issues Welcome Again

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#244]
User changed regions within the bot room and was then welcomed by the bot each time they changed (in general room).

**Comment by otter-computer** [comment]
Sadly this is because the `addRole` and `removeRole` functions in the library are unreliable so we have to remove *all* the roles and then re-add them. I guess this is what causes the side effect of being welcomed again by having your member role added and removed.

**Comment by jmariondev** [comment]
That's strange? Are we doing a commit of roles when we remove them all, then committing the adds? I implemented the welcome handler so it checks that the difference between `oldUser` and `newUser` includes the addition of 'Member'.

**Comment by otter-computer** [comment]
I don't think we're doing 2 separate actions, but we're overwriting all the old roles with the new ones.

**Comment by jmariondev** [comment]
Yeah I checked the `!setregion` command and nothing changed there. If I can repro this later I'll have a peek.

**Comment by jmariondev** [comment]
Reproduced this in prod as well as JunkBot, looks like a change in discord.js. When I first tested on JunkBot, the issue wasn't present. Once I re-ran an `npm install` I got the issue. I'll try to find what changed.

**Comment by jmariondev** [comment]
Confirmed that the issue is not present when I explicitly use discord.js 11.0.0, and is present when I use discord.js 11.1.0.

It looks like `oldMember` only gets one of the actual member's roles? The only change made here is the removal of 'Asia' and addition of 'Europe'.

```
[2017-05-11T05:09:02.914Z] oldMember's roles:
[2017-05-11T05:09:02.914Z] @everyone
[2017-05-11T05:09:02.915Z] Asia
[2017-05-11T05:09:02.915Z] undefined

[2017-05-11T05:09:02.915Z] newMember's roles:
[2017-05-11T05:09:02.916Z] @everyone
[2017-05-11T05:09:02.916Z] Moderator
[2017-05-11T05:09:02.916Z] Member
[2017-05-11T05:09:02.917Z] Europe
[2017-05-11T05:09:02.917Z] undefined
```

If we're unable to remedy this, we can explicitly stay on 11.0.0. I do think, however, that we made 11.1.0-specific changes for #232? We may need to revert these to accomplish a pinned version.

**Comment by otter-computer** [comment]
How weird...

Might be worth opening a ticket over on the Discord.js GitHub, ask if something weird is going on or it's just our shitty code.

Also could be worth our time investigating whether the `addRole` and `removeRole` functions actually work like we want them to now, or if that was *also* just our shitty code too 🙃

**Comment by ghost** [comment]
I've tested using `removeRole` and then `addRole` and it works fine for me, I managed to use it for changing region. And it doesn't issue Welcome Again anymore. What was the problem before?

```javascript
message.member.removeRole(oldRegion)
  .then(member => {
    member.addRole(newRegion);
  });
```

**Comment by jmariondev** [comment]
Yeah, that solution used to ignore the removal of roles, I imagine because of caching. I'll confirm this when I get back to my computer that has JunkBot's access token on it.

**Comment by ghost** [comment]
Damn, what a shame. It was working fine in my test server but I don't know if there other conditions that trigger it.

**Comment by jmariondev** [comment]
I'll still give it a go when I can 😄

**Comment by LuaMilkshake** [comment]
See #271. I would have pushed to your branch but I didn't have push access to it. soz

**Comment by otter-computer** [comment]
There is no welcome message anymore 🤓
