### ISSUE TITLE
Add a command to create a role

### ISSUE THREAD

**Issue by ghost** [otter-computer/GaymersBot#250]
A new command that would allow an admin to create a role with specific parameters without using the server settings interface.

The parameters to specify are here: https://discord.js.org/#/docs/main/stable/typedef/RoleData

My idea for this was to allow the admin to create game roles very quickly so that they can just pull a list of popular multiplayer games and convert them into roles without much hassle.
And since all of these roles would have the same parameters except for the name, the command could simply be `!role create name roleclass` where `roleclass` is the name for a set of pre-defined parameters, like `gamerole`: `!role create Terraria gamerole`.

**Comment by chrislennon** [comment]
👍 I like this idea, though should get feedback from the admins & mods if they see any issue - likely not.

FYI - there was a lot of work done on the roles module yesterday on #249 may want to check you don't conflict. In essence I removed the set/unset/add/remove verbs.

I would probably suggest a separate command e.g. `!createrole` or something. This means command can be restricted to admins & mods easier.

**Comment by brandon-a** [comment]
I agree, this is a good idea, additionally the game roles all have no permissions and have "Allow anyone to @mention this role." enabled. And I also agree with @chrislennon seperating it into an admin / mod only command would be ideal.
