### ISSUE TITLE
Removal of #welcome-room

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#256]
Certain events recently have resparked the conversation around the removal of the welcome room. This is a ticket to include any functionality that will need to be considered if this goes ahead.

Affected code:
- Remove `Member` role from restricted roles in `roles.js`, will not be required anymore.
- `memberJoined`  event will need to be rewritten to handle a straight welcome in `#general`.
- `memberLeft` has code that touches the welcome room to clean up messages if a user leaves before being given a `Member` role.
- Will remove `!member` command, will be unnecessary if we have no need for a `Member`  role (closes #220)
- Any filtering on what roles a user must have when trying to interact with the bot must be rewritten. Bot should only ignore if an ignore role is applied (e.g. Restricted or Bot Restricted)

Issues relating to MercyBot with regards to `#welcome-room` removal can be found [here](https://github.com/ThomasShaped/MercyBot/issues/22).

**Comment by otter-computer** [comment]
To sum up what was discussed in #moderators last night, we had a few proposals put forward to address what could be done as an alternative:

# Use bot to add `Member` role to all new members on join
Users will be granted automatic membership when they join. This means minimal change to the current workings of the server, just an update to the bot's functionality on member join events. This will mean that server pruning will no longer be possible using the inbuilt Discord functionality.

# Have members type `!agree` in order to be given the `Member` role
This will mean users must read and agree to the rules before they are granted the `Member` role. The bot will then give them the `Member` role once the command is run. This would mean members have to actually read the rules, but it could be seen as a hostile/unfriendly welcome.

# Remove `Member` role altogether and allow members to join straight to `#general`
This would remove all barriers to entry altogether, other than Discord's inbuilt ones, allowing users to join directly to `#general`. This will have the least entry friction, but will mean that trolls are immediately able to post in all channels. This will require some permission updates to the `Restricted` role, ensuring it is given `deny` permissions on each channel.

**Comment by ghost** [comment]
Sorry, testing things for work. 🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️
