### ISSUE TITLE
Bin cronjobs

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#264]
What's our plan with cronjobs? They're commented out on master right now. Are we going by 'crons are evil' and we're just going to get rid of them?

**Comment by otter-computer** [comment]
Yeah, crons are evil and will probably be superceded by SQS messages if we need anything to be run on a timer. That's already been implemented in Mercy and seems to be working really well.

**Comment by jmariondev** [comment]
Then the PR is already hot and fresh 😉 .
