### ISSUE TITLE
Region Aliases

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#266]
Sometimes we'll see people use `!setregion EU` (or NA, etc). It might be nice to support this in our `!setregion` command.

**Comment by chrislennon** [comment]
Any idea what we want for the other ones? or just EU & NA?
```
Europe - EU
North America - NA
South America - SA
Oceania - OCE
Africa - AF
Asia - AZ
Middle East - ME
```

**Comment by jmariondev** [comment]
Probably some common ones like
```
North America - NA, US, (maybe CA?)
Oceania - OCE, AU, NZ
```
