### ISSUE TITLE
Joined command specific date/time

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#273]
Much salt around the 'rounding' of moment.js's natural language output. Request to append the specific date & time a user joined.

**Comment by chrislennon** [comment]
Correction: the specific date is already there, it just doesn't display on mobile 😄

**Comment by chrislennon** [comment]
<img width="493" alt="joined-diff" src="https://cloud.githubusercontent.com/assets/9197696/26392372/ad184cd6-4066-11e7-995b-20a595200726.png">

**Comment by otter-computer** [comment]
The embed footer displays that time in the user's local timezone. If we were to integrate it into the body of the message we'd have to display it in UTC or whatever instead 😭
