### ISSUE TITLE
Additional information in message-logs and user-logs

### ISSUE THREAD

**Issue by jmariondev** [otter-computer/GaymersBot#276]
We can glean some additional information for the events in message-logs and event-logs from Discord's audit logs. One example of this is adding the user that deleted a message to a message delete event. I imagine we can associate a message delete event with an audit log event. There are likely other instances where we can get useful info from these logs.

**Comment by chrislennon** [comment]
raised for discussion on the admin repo, also pending next revision of Discord.js in #289
