### ISSUE TITLE
Issue tidy/move

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#280]
Propose to move/update the following issues to (or with info from) the administration repo - please report back with orders 🖖 :
- #256 
- #235 
- #194 
- #171 
- #170

**Comment by jmariondev** [comment]
Perhaps 'sister' issues on the admin repo are more appropriate? Many of these are still technical in nature and discuss the actual bot implementation of the policy change.

**Comment by otter-computer** [comment]
- #256 is still under discussion in gaymers-discord/administration#4
- #235 I'd like to keep open in Icebox for now, is something that should be brought over to the admin repo for discussion still
- #194 👎 
- #171 👎 can be closed for now. Can reopen if we really want it back.
- #170 👎

**Comment by jmariondev** [comment]
I still insist that #170 should at least remain open. Discord's permissions system is batshit insane and we should have our own way of making sure that our intentions are clearly represented in the Swahili hieroglyphs that is their ACL system.

**Comment by otter-computer** [comment]
@LuaMilkshake but I was looking forward to another open/close war 😢
