### ISSUE TITLE
Fetch Server Rules from Markdown file on GitHub

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#282]
It would be super awesome to be able to fetch the server rules from the Markdown file we store in the administration repo and have the bot render it out nicely in the #info-rules channel.

This would allow for flexible updates to the server rules, at the moment only @brandon-a can update the server rules manually and that's a bit of a pain whenever we want to make a change.

It would also make for a much more pleasant reading experience - embeds yes please - as at the moment it's just a big wall o' text.

GitHub API integration would also pave the way for future communication between the bots and GitHub, so it should be kept in mind while building if possible that this will not be the extent of the functionality we would like.

If access tokens are required I will investigate if we can create an org-level one, otherwise I can just generate a personal access token myself and drop it in.

**Comment by chrislennon** [comment]
Points for discussion:
- replacing the original rules message is only possible if the client was on when the message was created, as per [this documentation](http://discordjs.readthedocs.io/en/latest/docs_textchannel.html#lastmessage) - there may be alternate ways around this.
- output of the message requires the message to be <2000 characters, we will need to split it in some way, if we split it dynamically this could lead to strange text splitting, probably best to split on a markdown element

**Comment by chrislennon** [comment]
Both of the above issues are now corrected.
- will bulk delete 20 previous messages in channel
- will split output messages on `---`

PR ready for review.
