### ISSUE TITLE
Welcome Back

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#285]
Implementation of lookup if userid previously exists on server to state welcome back (maybe also moderation channel flag).

Keep an eye out for the fact that once a member joins they are in the member list. Maybe its best to look at the original joined date and compare it with the current timestamp.

Suggested by: @Genovi

**Comment by chrislennon** [comment]
Was thinking about this issue when dealing with other the other welcome issue we have.

My perception was that we had a mechanism for retrieving all users that had ever been on the server (despite them leaving) - I recall this in reference to a discussion that someone said we had >3000 users (in the client cache?).

Am I talking out my ass by remembering this incorrectly? Can someone point me to the discord.js docs that cover this part? 
I suspect these users are held in the way described but lost when the bot restarts/redeploys - in which case we could provide this information in the welcome message i.e. welcome back! But it may not be accurate 100% of the time.

//CC: @codermess, @thomasshaped, @luamilkshake

**Comment by jmariondev** [comment]
The only thing similar to that would be the client cache which I think is both of a fixed length and is also lost on restart. There's definitely no "pull everyone that's ever been" as that number is in excess of 10,000 according to Brandon.

**Comment by chrislennon** [comment]
Okay, I misunderstood the context of the number that was thrown around previously. With that in mind if we wish this feature I would suggest we instigate the users database again, here is how i would approach it:

- SQS or API Gateway (backed by Lambda) to update user record on an join/leave event
  - Initially, to catch all legacy users, we may need to look at mass import, or do it on online/offline status change for a while
- Change the bot's welcome logic to incorporate an API lookup on that user, modifying if the user already exists - prior to creating their record

Other considerations:
- welcome room removal #256 
- Additional functionality that we could obtain from this:
  - website avatars can be populated (this functionality previously existed)
  - website roles can be updated/displayed
  - anything else?

**Comment by chrislennon** [comment]
Lots of work been conducted on this today, looks like should be hitting the bot today (or at the latest this weekend).

<img width="589" alt="returning_user1" src="https://user-images.githubusercontent.com/9197696/27487878-5cf09984-5835-11e7-8bf5-ba413560a01b.PNG">

<img width="292" alt="returning_user2" src="https://user-images.githubusercontent.com/9197696/27487882-60e99d7e-5835-11e7-87d7-b8b881daddb5.PNG">
