### ISSUE TITLE
Add command requester to !avatar and !joined response

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#287]
The `!joined` and `!avatar` commands can have the unintended feeling of "stalking" a user when the commands are issued and subsequently deleted.

Proposal - to append a mention of the user who issued the command to the response that the bot responds with.

Up for discussion.
//cc @gaymers-discord/staff

**Comment by TimC3PO** [comment]
I totally support this change. It's super awkward when people pull up your Avatar and delete the command.. I could only imagine how creepy it is for regular users who don't have logs to review.

**Comment by Reynbow** [comment]
Agreed! Clever idea.

**Comment by Tookseh** [comment]
100% behind this idea. Here's looking at you, Prince Set.

**Comment by TimC3PO** [comment]
LMAO Tooks. You're so right.
