### ISSUE TITLE
Include name of user that deleted a message

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#289]
In the example where an Admin or Moderator deletes a message of a user, we should state this in the message sent to message-logs channel for clarity.

This functionality is detailed on a [discord.js isssue](https://github.com/hydrabolt/discord.js/issues/1520), is currently available in the `11.1-dev` branch (which we can move to if desired) or we can wait for the 11.2 stable release.

**Comment by chrislennon** [comment]
Implemented in 11.2 https://github.com/hydrabolt/discord.js/commit/712305dece0aaae0d6883757a78c772a07d2c39c

Full [release notes](https://github.com/hydrabolt/discord.js/releases/tag/11.2.0)

**Comment by ghost** [comment]
Don't know if this is a big enough reason for moving into 11.2, are there other changes in the changelog we're interested in?

**Comment by otter-computer** [comment]
@coderMess dunno if there’s much else in disco that’s waiting on 11.2, but there’s this pr in Mercy that’s waiting for it https://github.com/gaymers-discord/MercyBot/pull/54

Tbh we might as well upgrade anyway. Hopefully not many breaking changes.

**Comment by ghost** [comment]
I see! Well, whenever it is upgraded I can get back to this. I could open an issue for the upgrade to do a round of testing before we push it to live.
