### ISSUE TITLE
Fix for Welcome message duplication

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#296]
So this bug happens in a few places #244 and also in Mercy [#36](https://github.com/gaymers-discord/MercyBot/issues/36)
In essence at restriction of a user (Mercy) or as we remove/re-add regions - we remove & re-add the member role. This triggers off the member welcome message again (also any other events attached to that, DMs etc)

Proposal:
- Keep the member status as it is but remove the Discobot from listening to it.
- Extend the member command to add a new 'welcome' role (and 'member' role.)
- Inform the Mods/Admins that 2 roles should be applied on approval of a member. (or potentially chain the role additions - below)
- Rewrite the welcome listener to listen for adding a role of welcome, issue the message then remove the role. (could potentially also then add the member role here)

Do we think this will cover all the eventualities we have encountered?

**Comment by otter-computer** [comment]
Possible solution: Check if the old member has roles or not. If they have no roles you can *pretty much* accept that they're new to the server. If they had roles then it's most likely that they've been restricted.

Edge case: They don't have any other roles besides member and an admin/mod removes the restricted role before adding the member role back.
