### ISSUE TITLE
Under-18 Persistence

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#300]
Issue occurs when a user rejoins the server that previously had the under-18 status, this status should be automatically readded to them so moderation doesn't need to remember or look this up every time.

This will involve holding the users status as part of a their record in the database, the only way that reference should be removed is when the discord role is removed by mod/admin, not by Server leave/join

**Comment by otter-computer** [comment]
Moved to Mercy board (https://github.com/gaymers-discord/MercyBot/issues/63)
