### ISSUE TITLE
Bot crashes when attempting to DM someone that has "Allow DM from this server" privacy setting disabled.

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#312]
Bot crashes when attempting to DM someone that has "Allow DM from this server" privacy setting disabled.

<img width="465" alt="screen shot 2017-06-30 at 21 28 46" src="https://user-images.githubusercontent.com/2439407/27751130-267b1ef0-5ddb-11e7-8552-d66e6c02a1a0.png">

**Comment by chrislennon** [comment]
corresponding bot error
```
[2017-06-14T23:18:18.917Z] (node:27078) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Explicit content cannot be sent to the desired recipient(s)
```

**Comment by chrislennon** [comment]
We could also augment the message we send back to them 'Check your DMs' - to something more appropriate, a user this morning was complaining that they never received the messages and I suspect they have privacy enabled.
