### ISSUE TITLE
Automatic Member status after time period

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#315]
Discussed in https://github.com/gaymers-discord/administration/issues/21

Add functionality to give users membership status after x minutes.

**Comment by chrislennon** [comment]
More information provided as part of this [ticket](https://github.com/gaymers-discord/administration/issues/23)

> 10-15 minutes after a user joins, a timer is fired. If the user has not said anything since joining, the bot mentions them again in welcome-room reminding them to introduce themselves. If the user has said something, the bot sends a message to mod-tracker with @here reminding staff to take a look at the welcome-room. If the user was manually caught before the timer, obviously no action is taken.

**Comment by jmariondev** [comment]
#134 will be implemented instead.
