### ISSUE TITLE
Animated avatars not appearing correctly

### ISSUE THREAD

**Issue by ghost** [otter-computer/GaymersBot#345]
Pulling an animated avatar with the !avatar command shows a static frame from the animation.
@ThomasShaped suggested checking whether it should stop using an embed.

**Comment by chrislennon** [comment]
Snicking my nose in cause I still have notifications turned on here xD

There has been some discussion on [discord.js](https://github.com/hydrabolt/discord.js/search?q=gif&type=Issues) about this. 

From a quick check (without a bot) its probable that the .avatarURL is either:
- returning a `.png`
- returning a url that isnt being recognised as/appended with  `.gif`
- could also be an embed issue ofc

Stealing @ThomasShaped avatar (using web client) gives me [this](https://cdn.discordapp.com/avatars/120897878347481088/a_7d8b452c7f890e1a2b03a7e1a98b5632.png) though correcting it to .gif [corrects it](https://cdn.discordapp.com/avatars/120897878347481088/a_7d8b452c7f890e1a2b03a7e1a98b5632.gif)

Double check the output from .avatarURL, if it looks correct its likely embeds at fault.

**Comment by ghost** [comment]
Thanks for the input! I hadn't looked into the avatar command before so I had no idea where the issue could be. I'll test around.

**Comment by otter-computer** [comment]
Fixed in #347
