### ISSUE TITLE
Users confused that adding role = pings

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/GaymersBot#353]
Users get `:angryping:` when they add a role to themselves but don't realize that comes with added `@mentions`. We should probably update the text that comes with the welcome message and `!role` command to include this info.

**Comment by ghost** [comment]
I'm not sure what you mean with this. Is it that new users don't know that roles can be pinged?

**Comment by otter-computer** [comment]
Yes, new users add roles to themselves but don’t realise that they can be mentioned using them, leading to annoyance!

**Comment by ghost** [comment]
Well, it was actually clear in the title of the issue. Oops. Thanks for the clarification. Sounds like a good idea.
