### ISSUE TITLE
Chancla command, pls <3

### ISSUE THREAD

**Issue by TatorSalad-zz** [otter-computer/GaymersBot#94]
A Chancla command would be lovely, with the 👡 emoji, since its the best fitting one i guess. Make one of the random messages say "estoopid" too.

**Comment by brandon-a** [comment]
chancla?

**Comment by jmariondev** [comment]
Latina moms sometimes use their flip-flops to discipline their kids, the word for flip-flops is "chanclas". 😆 

https://www.youtube.com/watch?v=EZfrE2JS8tg

**Comment by TatorSalad-zz** [comment]
I spelled it wrong, I meant chancla. Spazer said I should submit and issue and he'll get around to it at some point

**Comment by jmariondev** [comment]
What should the message be with this command? Perhaps messages in Spanish?

**Comment by brandon-a** [comment]
I feel like this command could be potentially offensive to some members.

**Comment by TatorSalad-zz** [comment]
There is no way it would be offensive to anyone.
Lua message me tomorrow on discord and we can collaborate on the messages.
